### ISSUE TITLE
release.yaml section named $pkg-release instead of $pkg when releasing 3rd-party package

### ISSUE THREAD

**Issue by ktossell** [ros-infrastructure/bloom#182]
I used the instructions at http://ros.org/wiki/bloom/Tutorials/ReleaseThirdParty to release libuvc, an external library. Everything went fine until the actual release, at which point the following lines were inserted into my hydro/release.yaml:

```
libuvc-release:
  tags:
    release: release/hydro/{package}/{version}
    url: https://github.com/ktossell/libuvc-release.git
    version: 0.0.1-3 
```

The CI job then failed because it couldn't find a "libuvc-release" package. (The section should have been named just "libuvc", which is the name of the package in package.xml.)

Pull request: https://github.com/ros/rosdistro/pull/1276
