### ISSUE TITLE
Support specifying custom dependencies (not via rosdep)

### ISSUE THREAD

**Issue by AAlon** [ros-infrastructure/bloom#525]
This would be some kind of dependency manifest which would look similar to the format of the `base.yaml` file but with ROS distro mapping, for example:

`dependency_manifest.yaml`
```
kinetic:
   aws_common:
       ubuntu: [ros-kinetic-aws-common]
melodic:
  aws_common:
      ubuntu: [ros-melodic-aws-common]
      debian:
          stretch: [ros-melodic-aws-common]
```
`bloom-release <key> --track .. --rosdistro .. --custom-dependencies dependency_manifest.yaml`

I suggest rosdep rules would still take precedent, so if we have two conflicting values - whatever's in `distribution.yaml` / `base.yaml` would apply. 

Advantages:
* Support multiple distros, hence would make it easier to automate the release
* No need to modify system wide dependency configuration for releasing packages
* Explicit - less prone to human error

Related to https://github.com/ros/rosdistro/pull/20670
