### ISSUE TITLE
Is Packages Dictionary Really Necessary for rosdistro

### ISSUE THREAD

**Issue by eitanme** [ros-infrastructure/bloom#64]
I'm not totally sure whether this is the right place for this, but here goes. In looking at the new rosdistro file format, I've noticed that the packages list is actually a dictionary as shown below:

```
ros_comm:
    url: git://github.com/ros-gbp/ros_comm-release.git
    version: 1.9.29-0
    packages:
      roscpp: clients/roscpp
      rospy: clients/rospy
      rosgraph_msgs: messages/rosgraph_msgs
      std_srvs: messages/std_srvs
      ros_comm: ros_comm
      rosbag: tools/rosbag
      rosconsole: tools/rosconsole
      rosgraph: tools/rosgraph
      roslaunch: tools/roslaunch
      rosmaster: tools/rosmaster
      rosmsg: tools/rosmsg
      rosnode: tools/rosnode
      ...
```

This seems to be unnecessary to me since catkin_pkg allows you to discover where the packages are in a given repository, along with their path information. Encoding it manually like this just leaves room for confusion and error. I'll make the suggestion that the packages list should move to being a white-list of package names that should be released from a given repository. I'll also include a code snippet to find all packages in a directory using catkin_pkg and throw them into a dict with the package name as the key:

``` python
import os
from catkin_pkg import packages as catkin_packages

def get_repo_packages(repo_folder):
    paths = []
    #find wet packages
    paths.extend([os.path.realpath(os.path.join(repo_folder, pkg_path)) \
                     for pkg_path in catkin_packages.find_package_paths(repo_folder)])

    #Remove any duplicates
    paths = list(set(paths))

    packages = {}
    for path in paths:
        pkg_info = catkin_packages.parse_package(path)
        packages[pkg_info.name] = path

    return packages

```

And the distro would become:

```
ros_comm:
    url: git://github.com/ros-gbp/ros_comm-release.git
    version: 1.9.29-0
    packages: [roscpp, rospy, rosgraph, std_srvs, ...]
```

Also, why are there some repositories that don't list packages at all? It seems kind of brittle to make the assumption that if the packages field is missing, that correlates to the repository name matching the package name that you would like to include in your white-list. It would be much more explicit to always require the white list or to just do away with the list altogether and require all packages in a repo to be released together... sort of like stacks used to enforce.

Example:

```
actionlib:
    url: git://github.com/ros-gbp/actionlib-release.git
    version: 1.9.8-0
```

Should probably be:

```
actionlib:
    url: git://github.com/ros-gbp/actionlib-release.git
    version: 1.9.8-0
    packages: [actionlib]
```

Thoughts?
